name: Lint
on: [push]
jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: |
                  node --version
                  npm --version
            - name: set @bitregistry translation-help
              run: npm config set '@bit:registry' https://node.bit.dev

            - name: npm install
              run: npm ci

            - uses: actions/setup-node@v1
              run: npm run eslint:github-action
